NAME_LABEL_L2 = {
    'Urban': 0,
    'Woodland and forest': 1,
    'Cropland': 2,
    'Grassland': 3,
    'Heathland and shrub': 4,
    'Wetland': 5,
    'Marine inlets and transitional waters': 6,
    'Sparsely vegetated land': 7,
    'Rivers and lakes': 8,
    'Sea': 9,
    'Montane': 10,
}

REASSIGN_NAME_LABEL_L3L2 = {
    'Urban': (0, 0),
    'Broadleaved Mixed and Yew Woodland': (1, 1),
    'Coniferous Woodland': (2, 1),
    'Sea': (3, 9),
    'Arable and Horticulture': (4, 2),
    'Improved Grassland': (5, 3),
    'Neutral Grassland': (6, 3),
    'Calcareous Grassland': (7, 3),
    'Acid Grassland': (8, 3),
    'Bracken': (9, 3),
    'Dwarf Shrub Heath': (10, 4),
    'Fen, Marsh, Swamp': (11, 5),
    'Bog': (12, 5),
    'Littoral Rock': (13, 6),
    'Littoral Sediment': (14, 6),
    'Montane': (15, 10),
    'Standing Open Waters and Canals': (16, 8),
    'Inland Rock': (17, 7),
    'Supra-littoral Rock': (18, 7),
    'Supra-littoral Sediment': (19, 7),
}

NAME_ABB_L2 = {
    'Urban': 'U',
    'Woodland and forest': 'WLF',
    'Cropland': 'CL',
    'Grassland': 'GL',
    'Heathland and shrub': 'HS',
    'Wetland': 'WL',
    'Marine inlets and transitional waters': 'MITW',
    'Sparsely vegetated land': 'SVL',
    'Rivers and lakes': 'RL',
    'Sea': 'S',
    'Montane': 'M',
}

REASSIGN_LABEL_NAME_L3 = {
    0: 'Urban',
    1: 'Broadleaved Mixed and Yew Woodland',
    2: 'Coniferous Woodland',
    3: 'Sea',
    4: 'Arable and Horticulture',
    5: 'Improved Grassland',
    6: 'Neutral Grassland',
    7: 'Calcareous Grassland',
    8: 'Acid Grassland',
    9: 'Bracken',
    10: 'Dwarf Shrub Heath',
    11: 'Fen, Marsh, Swamp',
    12: 'Bog',
    13: 'Littoral Rock',
    14: 'Littoral Sediment',
    15: 'Montane',
    16: 'Standing Open Waters and Canals',
    17: 'Inland Rock',
    18: 'Supra-littoral Rock',
    19: 'Supra-littoral Sediment',
}

L2_L3_NAME = {
    'Urban': ['Urban'],
    'Woodland and forest': ['Broadleaved Mixed and Yew Woodland', 'Coniferous Woodland'],
    'Cropland': ['Arable and Horticulture'],
    'Grassland': ['Improved Grassland', 'Neutral Grassland', 'Calcareous Grassland', 'Acid Grassland', 'Bracken'],
    'Heathland and shrub': ['Dwarf Shrub Heath'],
    'Wetland': ['Fen, Marsh, Swamp', 'Bog'],
    'Marine inlets and transitional waters': ['Littoral Rock', 'Littoral Sediment'],
    'Sparsely vegetated land': ['Inland Rock', 'Supra-littoral Rock', 'Supra-littoral Sediment'],
    'Rivers and lakes': ['Standing Open Waters and Canals'],
    'Sea': ['Sea'],
    'Montane': ['Montane']
}